The Spatio-Temporal Path system
idaholab/malamute pull request #117
Opened 2023-12-06 04:23 UTC by hugary1995

close #116

This PR adds a new system associated with the syntax block `[SpatioTemporalPaths]`. Multiple SpatioTemporalPath-derived objects can be added under that syntax block. I have implemented 3 objects so far:

- `PiecewiseLinearSpatioTemporalPath`: This one accepts input file vectors `t`, `x`, `y`, `z` and constructs a spatio-temporal path object.
- `CSVPiecewiseLinearSpatioTemporalPath`: This one is similar to the previous one but instead reads from a csv file.
- `FunctionSpatioTemporalPath`: This one accepts moose functions for `x`, `y` and `z`.

Once a `SpatioTemporalPath` object is constructed, other `MooseObject`s can retrieve path given its name from the warehouse, through the `SpatioTemporalPathInterface` interface. See e.g. `ADMovingHeatSource` for how that coupling works.

Each spatio-temporal path objects recomputes several path-related information at every time step:

- `SpatioTemporalPath::position()` returns the current path front.
- `SpatioTemporalPath::velocity()` returns the current path moving velocity.
- `SpatioTemporalPath::direction()` returns the current path direction.

Variants of the above methods exist which accepts a time and computes the corresponding path information at the specified time.

By default the path-related information is recomputed at every time step, i.e. the path information is "live". The users have control over how often the path-related information is updated by the parameter `update_interval`. There are also methods that retrieve the path-related information from the previous update:

- `SpatioTemporalPath::previousPosition()`
- `SpatioTemporalPath::previousVelocity()`
- `SpatioTemporalPath::previousDirection()`

An object deriving from `SpatioTemporalPath` only need to override one single method `Point position(Real t) const`. Default implementations are provided for `RealVectorValue velocity(Real t)` and `RealVectorValue direction(Real t)` which use finite-differencing to compute the derivatives. The developer can optionally override these methods to provide more efficient/accurate implementations.

Utility methods are provided to compute the tangential and normal components of the distance between a given point and the path's current position.

- `SpatioTemporalPath::tangentialDistance(const Point & p)`
- `SpatioTemporalPath::normalDistance(const Point & p)`

Similarly, variants of the above methods exist which additionally accepts a specified time.

Spatio-temporal paths are useful in many scenarios. I have added two concrete examples for demonstration purposes:

- `ADMovingHeatSource` and `ADMovingEllipsoidalHeatSource`
- `SpatioTemporalPathElementSubdomainModifier`

Their names are self-explanatory. Note that `ADMovingEllipsoidalHeatSource` makes use of the tangential and normal distance to effectively "rotate" the ellipsoidal heat source.

2023-12-12 22:59 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1925757/) on e66c5cb wanted to post the following:

View the site [here](https://mooseframework.inl.gov/malamute/docs/PRs/117/site)

This comment will be updated on new commits.

2023-12-12 23:00 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1925763/) on e66c5cb wanted to post the following:


## Coverage

<table>
  <thead>
    <tr>
      <th></th>
      <th>f43e33</th>
      <th colspan=4>#117 e66c5c</th>
    </tr>
    <tr>
      <th></th>
      <th>Total</th>
      <th>Total</th>
      <th>+/-</th>
      <th>New</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Rate</b></td>
      <td>68.98%</td>
      <td>71.94%</td>
      <td>+2.96%</td>
      <td>87.54%</td>
    </tr>
    <tr>
      <td><b>Hits</b></td>
      <td>1023</td>
      <td>1269</td>
      <td>+246</td>
      <td>246</td>
    </tr>
    <tr>
      <td><b>Misses</b></td>
      <td>460</td>
      <td>495</td>
      <td>+35</td>
      <td>35</td>
    </tr>
  </tbody>
</table>

[Diff coverage report](https://mooseframework.inl.gov/malamute/docs/PRs/117/coverage_diff)

[Full coverage report](https://mooseframework.inl.gov/malamute/docs/PRs/117/coverage)

## Warnings

- New new line coverage rate 87.54% is less than the suggested 90.0%



This comment will be updated on new commits.

2023-12-12 23:00 UTC, cticenhour requested changes
Thanks for this contribution @hugary1995! I can see this being incredibly useful.

Not done here quite yet, but I wanted to note my current progress since there is some low-hanging fruit to address. Will dive in more tomorrow!

2023-12-12 23:00 UTC, cticenhour commented on doc/content/source/materials/ADMovingEllipsoidalHeatSource.md
> +## Example Input File Syntax
Please add example input file syntax for each of these documentation files, for those objects present in the added tests. This applies to all the new documentation files except for the action and system pages.

2023-12-12 23:00 UTC, cticenhour commented on include/materials/ADMovingEllipsoidalHeatSource.h
> +  /// Process efficienty
```suggestion
  /// Process efficiency
```

2023-12-12 23:00 UTC, cticenhour commented on test/tests/spatiotemporal_path/tests
> +  [esm]
```suggestion
  [element_subdomain_modifier]
```
I am OK with the acronym being used in the input file naming, but would like this to be written out for the TestHarness output, since its an unfamiliar acronym to some.

2023-12-12 23:00 UTC, cticenhour commented on doc/content/syntax/SpatioTemporalPaths/index.md
> +# SpatioTemporalPath System
More of a general comment/question - have you thought about (or do you see) this system being applied to some of our current laser melting and laser welding examples? I wonder if there's some quality of life updates to be made in some of these older examples after this goes in....

2023-12-12 23:11 UTC, cticenhour reviewed
I think this will fix the current documentation failures.

2023-12-12 23:11 UTC, cticenhour commented on doc/content/source/actions/AddSpatioTemporalPathAction.md
> +This action registers objects derived from [`SpatioTemporalPath`](SpatioTemporalPath/index.md) into the current problem. See the linked page for more details on the usage of the `SpatioTemporalPath`
```suggestion
This action registers objects derived from [`SpatioTemporalPath`](SpatioTemporalPaths/index.md) into the current problem. See the linked page for more details on the usage of the `SpatioTemporalPath` system.
```

2023-12-12 23:11 UTC, cticenhour commented on doc/content/syntax/SpatioTemporalPaths/index.md
> +!syntax list /SpatioTemporalPath objects=False actions=True subsystems=False
```suggestion
!syntax list /SpatioTemporalPaths objects=True actions=False subsystems=False

!syntax list /SpatioTemporalPaths objects=False actions=False subsystems=True

!syntax list /SpatioTemporalPaths objects=False actions=True subsystems=False
```

2023-12-18 18:22 UTC, cticenhour requested changes
Alright, finally had time to finish this review. Thanks for this new feature! A couple more comments about parameter defaults and user documentation, but I think we'll be ready to go soon.

2023-12-18 18:22 UTC, cticenhour commented on src/spatiotemporalpaths/CSVPiecewiseLinearSpatioTemporalPath.C
> +  params.addParam<MooseEnum>("file_format", format_flag, "Set the file format (rows vs. columns).");
We should let the user know the default enum case for both of these params. I don't remember seeing such a mention in the documentation, so it should be done either here in the param description or in the markdown.

2023-12-18 18:22 UTC, cticenhour commented on src/spatiotemporalpaths/PiecewiseLinearSpatioTemporalPathBase.C
> +      "Raise an exception when trying to extrapolate.");
Again, should mention the default either here or in the documentation discussion.

2023-12-18 18:25 UTC, cticenhour commented
Just took a look at the coverage diff - could you also add some error checking tests? The majority of the diff is missing coverage on `mooseError` calls.

2025-05-21 16:05 UTC, cticenhour commented
@hugary1995 Taking some time this week to go through stale MALAMUTE PRs. Do you intend to continue development on this feature? It has been some time.

2025-05-21 16:44 UTC, hugary1995 commented
whoops I dropped the ball on this. I think we now plan to merge this capability into either blackbear or moose. We can close this PR now.

2025-05-21 16:44 UTC, closed without merging

2025-05-21 18:13 UTC, cticenhour commented
Thanks!