Yttria thermoelectric 128
idaholab/malamute pull request #133
Opened 2024-06-26 21:57 UTC by apb13

Skipped running the input files in this directory as instructed. Ensured comments were formatted correctly in the input files.
Refs #128

2024-07-02 17:11 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2302493/) on 5b730a0 wanted to post the following:


## Coverage

No coverage report(s) were found for the base commit 604877e836.
[Full coverage report](https://mooseframework.inl.gov/malamute/docs/PRs/133/coverage)



This comment will be updated on new commits.

2024-07-02 17:27 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2302487/) on 5b730a0 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/malamute/docs/PRs/133/site)

This comment will be updated on new commits.

2024-07-03 23:58 UTC, sapitts requested changes
Just a few spacing issues to address before this PR is ready to merge

2024-07-03 23:58 UTC, sapitts commented on examples/sps/multiapp/yttria_thermoelectric/reference_residual/constant_electric_potential/micro_yttria_thermoelectrical_aehproperties_refres.i
> +  #  checkpoint = true
Rather than leaving this commented out line in this input file, please remove the line

2024-07-03 23:58 UTC, sapitts commented on examples/sps/multiapp/yttria_thermoelectric/reference_residual/function_electricpotential/micro_yttria_thermoelectric_oneway.i
> +    constant_names = 'Z_cat   v_scale e '
Remember that the names and expression values (next line down) need to be vertically aligned. Please add the space in front of the `Z_cat` name back to maintain the vertical alignment

2024-07-08 13:29 UTC, apb13 commented
@sapitts Desired changes were made to the input files

2024-07-08 20:58 UTC, sapitts approved these changes

2024-07-08 20:58 UTC, merged