Tutorial MooseDoc and Images
idaholab/malamute pull request #164
Opened 2024-08-01 16:20 UTC by apb13

Uploading Markdown documentation and images for tutorial
Refs #145

2024-08-01 17:01 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/2362476/) on 4fe3e90 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/malamute/docs/PRs/164/coverage)



This comment will be updated on new commits.

2024-08-01 17:03 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/2362470/) on 4fe3e90 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/malamute/docs/PRs/164/site)

This comment will be updated on new commits.

2024-08-01 17:18 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2362493/) on 5823a45 wanted to post the following:

Warning: This PR changes repo size by 63.08 MiB.

2024-08-01 19:48 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2362618/) on 2621423 wanted to post the following:

Warning: This PR changes repo size by 126.24 MiB.

2024-08-02 00:03 UTC, sapitts requested changes
This PR now has all of the images added twice. Remove one of the directories so that all of the images are included only once

2024-08-02 15:10 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2363949/) on c20776c wanted to post the following:

Warning: This PR changes repo size by 63.23 MiB.

2024-08-02 16:40 UTC, sapitts requested changes
Try making these types of changes, as we discussed in our meeting. Also include the updates to the `!listing` command and the bibtex file

2024-08-02 16:40 UTC, sapitts commented on doc/content/media/tutorial_dcs5_images/tutorial_pngs/Picture1.png
Let's remove this file; it is a duplicate of the `toolset.png` file

2024-08-02 16:40 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
> +!media doc/content/media/tutorial_dcs5_images/tutorial_pngs/results_pngs/max_temp_vs_sim_time.png
```suggestion
!media media/tutorial_dcs5_images/tutorial_pngs/results_pngs/max_temp_vs_sim_time.png
```

2024-08-02 16:40 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
> +       id=max_temp_vs_sim_time
```suggestion
       id=max-temp-vs-sim-time
```

2024-08-02 17:33 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2364168/) on 30c3724 wanted to post the following:

Warning: This PR changes repo size by 63.21 MiB.

2024-08-02 17:53 UTC, sapitts commented on doc/content/tutorials/efas/introduction/content.md
> +!listing tutorials/tutorials/efas/introduction/dcs5_copper_constant_properties_electrothermal.i
too many tutorials in this file path 
```suggestion
!listing tutorials/efas/introduction/dcs5_copper_constant_properties_electrothermal.i
```
Make this change throughout the file

2024-08-02 17:56 UTC, sapitts requested changes

2024-08-02 17:56 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
> +    caption=Electric Field and Temperature Contour Plots for a 10 mm wall thickness at t = 960 seconds.
Remove the `t =` in this caption and all others
```suggestion
    caption=Electric Field and Temperature Contour Plots for a 10 mm wall thickness at a simulation time of 960 seconds.
```

2024-08-02 17:56 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
> +    caption=Electric Field and Temperature Contour Plots for a 10 mm wall thickness at t = 960 seconds.
Make this change for all the captions that have an equal sign to remove that equal sign

2024-08-02 17:56 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
> +    id=potential_temp_screenshot
update all the ids for the figures to use dashes instead of underlines
```suggestion
    id=potential-temp-screenshot
```

2024-08-02 18:15 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2364207/) on c85ddde wanted to post the following:

Warning: This PR changes repo size by 63.21 MiB.

2024-08-02 18:43 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2364371/) on bbc2007 wanted to post the following:

Warning: This PR changes repo size by 63.21 MiB.

2024-08-02 19:01 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
> +!media media/tutorial_dcs5_images/tutorial_pngs/results_pngs/25mm-elec-field-and-temp.png
try leaving this file path name with the underscores to match the file name you created in a previous commit:
```suggestion
!media media/tutorial_dcs5_images/tutorial_pngs/results_pngs/25mm_elec_field_and_temp.png
```

2024-08-02 19:14 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2364451/) on a45e8da wanted to post the following:

Warning: This PR changes repo size by 63.21 MiB.

2024-08-06 00:01 UTC, moosebuild commented
Job [Precheck](https://civet.inl.gov/job/2369210/) on 20a9807 wanted to post the following:

Warning: This PR changes repo size by 63.21 MiB.

2024-08-06 23:24 UTC, sapitts requested changes

2024-08-06 23:24 UTC, sapitts commented on doc/content/tutorials/efas/introduction/concluding_remarks.md
Looks like the only issue remaining is debugging this pagination command. Work on debugging this by carefully checking for spelling errors and by comparing against the final page for other tutorials

2024-08-07 16:51 UTC, apb13 commented
Tutorial meets my specifications and appears ready to merge. @sapitts

2024-08-07 20:38 UTC, sapitts submitted a review, later dismissed
The built website looks good to me. If you want to make one more change to the suggested input file names in the table (to make the names shorter) as we discussed during the poster session, that would be good

2024-08-08 14:38 UTC, sapitts approved these changes
Looks good to me

2024-08-08 14:38 UTC, merged