[WIP] Fill in MALAMUTE SQA documents
idaholab/malamute pull request #74
Opened 2023-05-15 21:24 UTC by cticenhour

Refs #73

2023-05-17 19:41 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1537918/) on 3016c85 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/malamute/docs/PRs/74/coverage)



This comment will be updated on new commits.

2023-05-17 19:42 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1536105/) on 5e70d81 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/malamute/docs/PRs/74/site)

This comment will be updated on new commits.

2023-05-18 07:08 UTC, lindsayad requested changes

2023-05-18 07:08 UTC, lindsayad commented on doc/content/sqa/malamute_cci.md
> +questions and inquires.
```suggestion
questions and inquiries.
```

2023-05-18 07:08 UTC, lindsayad commented on doc/content/sqa/malamute_scs.md
> +[the MOOSE Code Standards](sqa/framework_scs.md).
Is MOOSE correct here or should it be MALAMUTE? Maybe the header title should be MALAMUTE and then we say something about how it follows MOOSE code standards?

2023-05-18 07:08 UTC, lindsayad commented on doc/content/sqa/malamute_srs.md
> +can leveraged to allow for multiscale coupling to the micro- and nano-scale of a given experiment.
```suggestion
can be leveraged to allow for multiscale coupling to the micro- and nano-scale of a given experiment.
```

2023-05-18 15:57 UTC, cticenhour commented on doc/content/sqa/malamute_scs.md
> +[the MOOSE Code Standards](sqa/framework_scs.md).
Good idea - will adjust.

2023-05-18 16:00 UTC, cticenhour commented on doc/content/sqa/malamute_scs.md
> +[the MOOSE Code Standards](sqa/framework_scs.md).
```suggestion
## MALAMUTE Code Standards

!style halign=left
MALAMUTE follows the MOOSE code standards for all development. For information on file guidelines, naming conventions, example code,
doxygen documentation, and other tips, please see
[the MOOSE standard here](sqa/framework_scs.md).
```

2023-05-18 17:50 UTC, lindsayad approved these changes

2023-05-18 20:12 UTC, cticenhour commented
Thanks!

2023-05-18 20:13 UTC, merged