Update SPS phase-field and engineering scale two way example
idaholab/malamute pull request #86
Opened 2023-06-19 20:40 UTC by laagesen

Closes #85

2023-06-19 21:10 UTC, cticenhour requested changes

2023-06-19 21:10 UTC, cticenhour commented on examples/sps/multiapp/electrothermal_with_phase_field/twoway_initial_prototype/micro_yttria_thermoelectric_twoway.i
> +    z_positions = '  0   0   0   0'
```suggestion
    z_positions = '0   0   0   0'
```

2023-06-19 22:06 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1596540/) on 6b59c7d wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/malamute/docs/PRs/86/coverage)



This comment will be updated on new commits.

2023-06-19 22:07 UTC, moosebuild commented
Job [Documentation](https://civet.inl.gov/job/1596535/) on 6b59c7d wanted to post the following:

View the site [here](https://mooseframework.inl.gov/malamute/docs/PRs/86/site)

This comment will be updated on new commits.

2023-06-23 17:06 UTC, laagesen commented
Took a little while to get back to this because I was on travel most of this week, but should be good to go now

2023-06-23 17:43 UTC, laagesen commented
Please hold off merging for now, may have discovered another issue

2023-06-26 20:53 UTC, laagesen commented
Should be good to go now

2023-06-27 11:49 UTC, cticenhour approved these changes

2023-06-27 11:50 UTC, merged